buildkite: Use 1.13 build for update dependencies script
In #1900, we didn't update the `pipeline-update-deps.yml` file, so the
auto-dependency updater is pointing to an invalid image causing the
following error:

```
Pulling yarpc-go-1.12 ... error

ERROR: for yarpc-go-1.12  manifest for 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber:yarpc-go-yarpc-go-1.12-build-2848 not found: manifest unknown: Requested image not found
ERROR: manifest for 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber:yarpc-go-yarpc-go-1.12-build-2848 not found: manifest unknown: Requested image not found
Exited with 1
```

https://buildkite.com/uberopensource/yarpc-go/builds/2848#7b985c92-4e0f-47f7-a6e1-6541b4e03987

This updates the updater to use the 1.13 image.