observability: Log error codes in observability middleware
This minor change adds an `errorCode` field to the existing
observability middleware logs. Previously, codes would only appear in
the error field. This made it difficult to group logs by error codes
since the message is part of the string message.

Logs will now contain an additional `errorCode` field, ie:

```
...
error: "code:aborted message:this is my message"
errorCode: "aborted"
```