staticcheck: Address issues
This addresses the following staticcheck issues:

```
api/encoding/stream.go:26:2: func StreamOption.unimplemented is unused (U1000)
api/transport/transporttest/context.go:81:10: should use time.Until instead of t.Sub(time.Now()) (S1024)
encoding/protobuf/protoc-gen-yarpc-go/internal/lib/lib.go:670:24: error strings should not be capitalized (ST1005)
encoding/thrift/thriftrw-plugin-yarpc/fx_test.go:80:3: should replace loop with *procs = append(*procs, p.SingleProcedures...) (S1011)
internal/bufferpool/bufferpool_test.go:49:34: should use sink.String() instead of string(sink.Bytes()) (S1030)
internal/bufferpool/bufferpool_test.go:169:3: const numIterations is unused (U1000)
internal/clock/fake.go:37:2: field addLock is unused (U1000)
internal/crossdock/client/tchclient/behavior.go:36:5: var log is unused (U1000)
internal/crossdock/server/http/timeout.go:36:46: should use time.Since instead of time.Now().Sub (S1012)
internal/crossdock/server/tch/timeout.go:43:46: should use time.Since instead of time.Now().Sub (S1012)
internal/crossdock/server/yarpc/sleep.go:50:2: should use a simple channel send/receive instead of select with a single case (S1000)
internal/service-test/cmd.go:114:24: should use c.stdout.String() instead of string(c.stdout.Bytes()) (S1030)
peer/peerlist/list.go:187:3: unnecessary guard around call to delete (S1033)
peer/peerlist/v2/list.go:210:3: unnecessary guard around call to delete (S1033)
peer/roundrobin/peerring.go:33:5: var errUnavailable is unused (U1000)
peer/x/peerheap/heap.go:31:2: field transport is unused (U1000)
pkg/lifecycle/once.go:108:35: should use make(chan struct{}) instead (S1019)
pkg/lifecycle/once.go:109:35: should use make(chan struct{}) instead (S1019)
pkg/lifecycle/once.go:110:35: should use make(chan struct{}) instead (S1019)
router_test.go:230:6: func IgnoreTestRouterWithMiddleware is unused (U1000)
transport/grpc/outbound.go:54:2: field lock is unused (U1000)
transport/http/peer.go:58:34: should use make(chan struct{}) instead (S1019)
transport/http/roundtrip_test.go:66:2: should merge variable declaration with assignment on next line (S1021)
transport/tchannel/channel_outbound_test.go:295:3: field getOutbound is unused (U1000)
transport/tchannel/channel_transport.go:102:2: field name is unused (U1000)
transport/tchannel/peer.go:52:34: should use make(chan struct{}) instead (S1019)
transport/tchannel/transport.go:65:2: field initialConnRetryDelay is unused (U1000)
transport/tchannel/transport.go:66:2: field connRetryBackoffFactor is unused (U1000)
x/yarpctest/service.go:152:2: field closer is unused (U1000)
x/yarpctest/types/stream.go:70:2: redundant return statement (S1023)
x/yarpctest/types/stream.go:116:2: redundant return statement (S1023)
yarpcconfig/chooser.go:242:2: default case should be first or last in switch statement (ST1015)
yarpcconfig/chooser.go:296:2: default case should be first or last in switch statement (ST1015)
yarpcconfig/mock_transport_spec_test.go:148:6: type anyKitMatcher is unused (U1000)
yarpcconfig/mock_transport_spec_test.go:159:5: var anyKit is unused (U1000)
yarpcconfig/spec.go:294:25: error strings should not be capitalized (ST1005)
yarpcconfig/spec.go:481:25: error strings should not be capitalized (ST1005)
yarpcconfig/spec.go:526:25: error strings should not be capitalized (ST1005)
yarpcconfig/spec.go:583:25: error strings should not be capitalized (ST1005)
yarpcconfig/spec.go:639:25: error strings should not be capitalized (ST1005)
yarpctest/fake_transport_test.go:48:30: should use make(chan struct{}) instead (S1019)
yarpctest/fake_transport_test.go:70:30: should use make(chan struct{}) instead (S1019)
```

Only the first one (unused `unimplemented()` method) was ignored.