Downgrade apache/thrift back to a compatible verison
As part of #1868, 59d1c5211ade29c8f502b11b418ad2d948680b8c upgraded github.com/apache/thrift
from this commit's version (which is compatible with tchannel-go) to v0.13.0 (which is not,
even at compile-time).

This restores the correct version.

---

Previously, to use yarpc, importers had to use glide or dep, or include a `replace` directive
to forcibly downgrade thrift to this version, or nothing would build due to errors like:
```
go/src/go.uber.org/cadence/internal/common/thrift_util.go:29:38: not enough arguments in call to thrift.NewTSerializer().Write
have (thrift.TStruct)
want (context.Context, thrift.TStruct)
```
This is clearly sub-par.  It probably got into #1868, didn't fail (... concerningly), and simply
wasn't noticed.